### PR TITLE
[Feature] add compatibility conversion

### PR DESCRIPTION
**Pull request by QZGao**
Support 3.8<=python<3.10

### CODE REVIEW

**Comment by QZGao** [comment]
We need some review on the Type Checking errors for Python 3.10.

**Comment by CNSeniorious000** [comment]
Hang on, I will try to fix it later this week.

**Comment by QZGao** [comment]
Checks still doesn't work?

**Comment by CNSeniorious000** [comment]
working on it right now 🙌

**Comment by CNSeniorious000** [comment]
just released [v0.2.3.1](https://pypi.org/project/promplate/0.2.3.1/)

**Pull request merged**
